name: ExcelFormer
channels:
  - nvidia/label/cuda-11.6.0
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=2.1.0=py311h06a4308_0
  - aiohappyeyeballs=2.4.0=py311h06a4308_0
  - aiohttp=3.10.5=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=11.0.0=hda39474_2
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - attrs=23.1.0=py311h06a4308_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - blas=1.0=mkl
  - blinker=1.6.2=py311h06a4308_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cachetools=5.3.3=py311h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - catboost=1.2.3=py311h06a4308_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.16.0=py311h5eee18b_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py311hdb19cb5_0
  - cryptography=41.0.3=py311h130f0dd_0
  - cuda-cccl=12.1.55=0
  - cuda-command-line-tools=12.1.0=0
  - cuda-compiler=12.1.0=0
  - cuda-cudart=12.1.55=0
  - cuda-cudart-dev=12.1.55=0
  - cuda-cudart-static=12.1.55=0
  - cuda-cuobjdump=12.1.55=0
  - cuda-cupti=12.1.62=0
  - cuda-cupti-static=12.1.62=0
  - cuda-cuxxfilt=12.1.55=0
  - cuda-documentation=12.1.55=0
  - cuda-driver-dev=12.1.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-libraries-static=12.1.0=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=12.1.66=0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=12.1.55=0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=12.1.55=0
  - cuda-nvrtc=12.1.55=0
  - cuda-nvrtc-dev=12.1.55=0
  - cuda-nvrtc-static=12.1.55=0
  - cuda-nvtx=12.1.66=0
  - cuda-nvvp=12.1.55=0
  - cuda-opencl=12.1.56=0
  - cuda-opencl-dev=12.1.56=0
  - cuda-profiler-api=12.1.55=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=12.1.0=0
  - cuda-tools=12.1.0=0
  - cuda-version=12.4=h3060b56_3
  - cuda-visual-tools=12.1.0=0
  - cudnn=9.1.1.17=cuda12_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.7=py311hfdbb021_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.6=py311h06a4308_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - filelock=3.13.1=py311h06a4308_0
  - flatbuffers=24.3.25=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.4.0=py311h5eee18b_0
  - future=1.0.0=py311h06a4308_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - gds-tools=1.6.0.25=0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gobject-introspection=1.78.1=py311h42194e9_1
  - google-auth=2.29.0=py311h06a4308_0
  - google-auth-oauthlib=0.5.2=py311h06a4308_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h1b29801_1
  - grpc-cpp=1.48.2=h5bf31a4_0
  - grpcio=1.48.2=py311h5bf31a4_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtest=1.14.0=hdb19cb5_1
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - h5py=3.11.0=py311h865a13c_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.12.1=h70be1eb_2
  - huggingface_hub=0.24.6=py311h06a4308_0
  - icu=58.2=he6710b0_3
  - imbalanced-learn=0.12.3=py311h06a4308_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.28.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - keras=2.12.0=py311h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcublas-static=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcufft-static=11.0.2.4=0
  - libcufile=1.6.0.25=0
  - libcufile-dev=1.6.0.25=0
  - libcufile-static=1.6.0.25=0
  - libcups=2.4.2=ha637b67_0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcurand-static=10.3.2.56=0
  - libcurl=8.2.1=h91b91d3_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusolver-static=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libcusparse-static=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm14=14.0.6=hecde1de_4
  - libmagma=2.8.0=h0af6554_0
  - libmagma_sparse=2.8.0=h0af6554_0
  - libnghttp2=1.52.0=ha637b67_1
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnpp-static=12.0.2.50=0
  - libnvjitlink=12.1.55=0
  - libnvjitlink-dev=12.1.55=0
  - libnvjpeg=12.1.0.39=0
  - libnvjpeg-dev=12.1.0.39=0
  - libnvjpeg-static=12.1.0.39=0
  - libnvvm-samples=12.1.55=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.20.3=he621ea3_0
  - librsvg=2.54.4=h36cc946_3
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libthrift=0.15.0=h0d84882_2
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.6=h6a678d5_1009
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxgboost=2.1.1=h6a678d5_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - lightgbm=4.5.0=cuda_py3.11h78bd007_2
  - lightning-utilities=0.9.0=py311h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.8.0=h51420fd_0
  - matplotlib=3.9.2=py311h06a4308_0
  - matplotlib-base=3.9.2=py311h6fb44e5_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.10=py311h5eee18b_0
  - mkl_random=1.2.7=py311ha02d727_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.0.4=py311h5eee18b_0
  - multiprocess=0.70.14=py311h06a4308_0
  - mysql=5.7.24=he378463_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nsight-compute=2023.1.0.15=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy-base=1.23.5=py311hf175353_1
  - oauthlib=3.2.2=py311h06a4308_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - orc=1.7.4=hb3bc3d3_1
  - packaging=24.1=py311h06a4308_0
  - pandas=2.2.2=py311ha02d727_0
  - pango=1.50.7=h05da053_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - plotly=5.24.1=py311h92b7b1e_0
  - ply=3.11=py311h06a4308_0
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - prompt-toolkit=3.0.48=pyha770c72_0
  - protobuf=3.20.3=py311h6a678d5_0
  - psutil=6.0.0=py311h9ecbd09_2
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.8.0=py311h06a4308_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pyparsing=3.1.2=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h7a1cb2a_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-flatbuffers=24.3.25=py311h06a4308_0
  - python-graphviz=0.20.1=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - python_abi=3.11=2_cp311
  - pytorch-tabnet=4.1.0=pyhd8ed1ab_0
  - pytz=2024.1=py311h06a4308_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - qt-main=5.15.2=h5b8104b_9
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_0
  - requests-oauthlib=2.0.0=py311h06a4308_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.5.1=py311ha02d727_0
  - scipy=1.15.3=py311h525edd1_0
  - seaborn=0.13.2=py311h06a4308_2
  - setuptools=72.1.0=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py311h06a4308_0
  - tensorboard=2.12.1=py311h06a4308_0
  - tensorboard-data-server=0.7.0=py311h52d8a92_1
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.12.0=mkl_py311h34a0fa1_0
  - tensorflow-base=2.12.0=mkl_py311he5f8e37_0
  - tensorflow-estimator=2.12.0=py311h06a4308_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h5eee18b_0
  - tqdm=4.66.5=py311h92b7b1e_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - urllib3=2.2.2=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.3=py311h06a4308_0
  - wheel=0.43.0=py311h06a4308_0
  - wrapt=1.14.1=py311h5eee18b_0
  - xlsxwriter=3.1.1=py311h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py311h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.34.2
      - alembic==1.15.2
      - babel==2.17.0
      - backrefs==5.8
      - black==25.1.0
      - cfgv==3.4.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - datasets==3.0.1
      - dgl==2.1.0
      - diffusers==0.30.2
      - distlib==0.3.9
      - einops==0.8.1
      - fsspec==2024.2.0
      - ghp-import==2.1.0
      - greenlet==3.2.2
      - griffe==1.6.0
      - identify==2.6.8
      - idna==3.8
      - importlib-metadata==8.4.0
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - mako==1.3.10
      - markdown==3.7
      - markdown-exec==1.10.0
      - markupsafe==2.1.5
      - mergedeep==1.3.4
      - mike==2.1.3
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.4.0
      - mkdocs-gen-files==0.5.0
      - mkdocs-get-deps==0.2.0
      - mkdocs-glightbox==0.4.0
      - mkdocs-literate-nav==0.6.1
      - mkdocs-material==9.6.7
      - mkdocs-material-extensions==1.3.1
      - mkdocstrings==0.28.2
      - mkdocstrings-python==1.16.2
      - mypy==1.15.0
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.17.0
      - opencv-python==4.10.0.84
      - optuna==4.3.0
      - optuna-integration==4.3.0
      - paginate==0.5.7
      - pathspec==0.12.1
      - pillow==10.2.0
      - pluggy==1.5.0
      - pre-commit==4.1.0
      - pyarrow==17.0.0
      - pygments-ansi-color==0.3.0
      - pymdown-extensions==10.14.3
      - pytest==8.3.5
      - pytorch-frame==0.2.3
      - pyyaml==6.0.2
      - pyyaml-env-tag==0.1
      - regex==2024.7.24
      - ruff==0.9.9
      - safetensors==0.4.5
      - sqlalchemy==2.0.41
      - sympy==1.12
      - tabpfn==2.0.6
      - tabulate==0.9.0
      - termcolor==2.4.0
      - tokenizers==0.20.3
      - torch==2.5.1+cu121
      - torch-cluster==1.6.3+pt25cu121
      - torch-frame==1.7.5
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torch-spline-conv==1.2.2+pt25cu121
      - torchaudio==2.5.1+cu121
      - torchdata==0.8.0
      - torchmetrics==1.6.0
      - torchvision==0.20.1+cu121
      - transformers==4.46.2
      - triton==3.1.0
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - verspec==0.1.0
      - virtualenv==20.29.2
      - watchdog==6.0.0
      - xgboost==3.0.1
      - zipp==3.20.1
prefix: /home/skyler/miniconda3/envs/ExcelFormer
